name: Publish NuGet packages

on:
  workflow_dispatch:
    inputs:
      avaloniaMinorVersions:
        required: true
        default: '11.0; 11.1; 11.2'
        type: string

jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          8.0.x
          9.0.x

    - name: Make packages
      shell: pwsh
      run: |
        $avaloniaMinorVersions = $(${env:AVALONIA_MINOR_VERSIONS}.Split(";") | % { $_.Trim() })
        foreach ($ver in $avaloniaMinorVersions)
        {
          # dotnet restore --configuration Release --nologo --verbosity quiet -p:AvaloniaMinorVersion=$ver
          # if ($LastExitCode -ne 0)
          # {
          #   exit 1;
          # }          
          dotnet build --no-restore --configuration Release --nologo --verbosity quiet -p:AvaloniaMinorVersion=$ver
          if ($LastExitCode -ne 0)
          {
            exit 1;
          }
          dotnet pack ./AlexandreHtrb.AvaloniaUITest/AlexandreHtrb.AvaloniaUITest.csproj --nologo --verbosity quiet --configuration Release -p:AvaloniaMinorVersion=$ver
          if ($LastExitCode -ne 0)
          {
            exit 1;
          }
        }
      env:
        AVALONIA_MINOR_VERSIONS: ${{ inputs.avaloniaMinorVersions }}

    - name: Push packages to NuGet
      shell: pwsh
      run: |
        $nupkgs = @(Get-ChildItem "./AlexandreHtrb.AvaloniaUITest/bin/Release/" -File -Filter "*.nupkg" | % { $_.FullName })
        foreach ($filePath in $nupkgs)
        {
          dotnet nuget push $filePath --api-key $env:NUGET_API_KEY --source https://api.nuget.org/v3/index.json
          if ($LastExitCode -ne 0)
          {
            exit 1;
          }
        }
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        # para produção: NUGET_API_KEY, https://api.nuget.org/v3/index.json
        # para testes: QA_NUGET_API_KEY, https://apiint.nugettest.org/v3/index.json
